version: "3.7"
services:
  email_listener:
    container_name: email_listener
    image: thelay/imap-listener-slack-announcer:latest
    restart: unless-stopped
    ports:
      - "8000:80"
    env_file:
      - .env
